# vim ft=yaml

# After changing this file, check it on:
#   http://yaml-online-parser.appspot.com/

language: python
sudo: false

python:
- 2.7
- 3.5

before_install:
    - pip install -U pip
    - pip install numpy enum

script:
    - make test
